import { routePathToDocId } from "@/lib/cms/pageSchema";

const affiliateDisclosure = "Some links may be affiliate links. Pitchside may earn a commission from qualifying purchases at no additional cost to you.";

export const cmsSeedPages = Object.freeze({
  "/grassroots-football-app": {
    id: routePathToDocId("/grassroots-football-app"),
    routePath: "/grassroots-football-app",
    slug: "grassroots-football-app",
    status: "published",
    pageType: "hub",
    templateKey: "pitchside-product-hub",
    templateVersion: 1,
    title: "Grassroots Football App",
    seo: {
      metaTitle: "Grassroots Football App",
      metaDescription: "Explore Pitchside AI's private-beta football app for small-sided match stats, highlights, player records and recording workflows.",
      canonical: "/grassroots-football-app",
      robots: "index,follow",
    },
    hero: {
      eyebrow: "Product hub",
      h1: "Grassroots football app for the matches you actually play",
      intro: "Pitchside is being built for phone-recorded small-sided football: match stats, highlights, personal records and practical recording workflows during private beta.",
      primaryCta: { buttonText: "Join early access", buttonUrl: "/contact" },
    },
    blocks: [
      {
        id: "product-routes",
        type: "featureGrid",
        title: "Choose the part of Pitchside you need",
        items: [
          { title: "Match review", body: "Understand the complete weekly match-review result, from recording to supported output.", href: "/football-analysis-app" },
          { title: "Stats and leaderboards", body: "See how planned stats, personal history and leaderboards fit together.", href: "/football-stats-app" },
          { title: "Video analysis workflow", body: "Follow capture, upload, processing, review, correction and sharing.", href: "/football-video-analysis" },
          { title: "Phone recording setup", body: "Plan one-phone or two-phone recording setups with safety and consent in mind.", href: "/technology/football-recording-setup" },
        ],
      },
      {
        id: "current-status",
        type: "statusTable",
        title: "Current product status",
        headers: ["Area", "Current status"],
        rows: [
          { cells: ["Availability", "Private beta; subscriptions are not currently purchasable."] },
          { cells: ["Supported footage", "Suitable phone-recorded 5-a-side, 6-a-side and 7-a-side football footage is the current focus."] },
          { cells: ["Supported events being tested", "Goals, assists, saves, passes and tackles. Output should be reviewed before treating the match record as final."] },
          { cells: ["Pricing source", "Free is planned at £0 with one recording per month. Paid is planned from £4.99 weekly with one recording per week and Personal Clips."] },
        ],
      },
      { id: "pricing", type: "pricingTeaser", title: "Planned launch pricing", description: "Free and Paid are the planned app tiers. Weekly, monthly and annual are billing options for the same Paid tier." },
      { id: "cta", type: "callToAction", headline: "Get launch updates", description: "Join the early access list for Pitchside private-beta updates.", buttonText: "Join early access", buttonUrl: "/contact" },
    ],
    author: { name: "Abdullah Luqman", url: "/authors/abdullah-luqman" },
    reviewer: { name: "Dave Coombs", url: "/authors/dave-coombs" },
    publishedAt: "2026-07-23T00:00:00.000Z",
    updatedAt: "2026-07-23T00:00:00.000Z",
  },
  "/technology/football-recording-setup": {
    id: routePathToDocId("/technology/football-recording-setup"),
    routePath: "/technology/football-recording-setup",
    slug: "football-recording-setup",
    parentPath: "/technology",
    status: "published",
    pageType: "technology",
    templateKey: "pitchside-pitch-setup",
    templateVersion: 1,
    title: "Football Recording Setup",
    seo: {
      metaTitle: "How to Set Up Phones to Record a Football Match",
      metaDescription: "Set up one or two phones to record football, reduce blind spots and choose the right fence mount, post mount or tripod for your pitch.",
      canonical: "/technology/football-recording-setup",
      robots: "index,follow",
    },
    hero: {
      eyebrow: "Recording setup",
      h1: "How to set up your phone to record a football match",
      intro: "Plan one-phone and two-phone football recording setups with safe mounting, consent, blind spots and venue rules in mind.",
      primaryCta: { buttonText: "Join the launch list", buttonUrl: "/contact" },
    },
    blocks: [
      {
        id: "central-sideline-diagram",
        type: "pitchDiagram",
        title: "Central sideline coverage",
        description: "Two phones placed together near the halfway line, each angled across one half of the pitch.",
        pitchFormat: "Small-sided pitch",
        cameraStyle: "phone",
        cameras: [
          { id: "camera-1", label: "Phone 1", x: 42, y: 97, rotation: 290, markerRotation: 68, coverageAngle: 70, coverageDepth: 72 },
          { id: "camera-2", label: "Phone 2", x: 58, y: 97, rotation: 250, markerRotation: 112, coverageAngle: 70, coverageDepth: 72 },
        ],
        notes: ["Keep both phones mounted safely outside the playing area.", "Use the same landscape orientation and record settings on both phones."],
        caption: "Useful where a safe central touchline mounting point is available.",
      },
      {
        id: "diagonal-coverage-diagram",
        type: "pitchDiagram",
        title: "Diagonal coverage",
        description: "Phones at opposite ends of the pitch create crossing coverage and can reduce repeated blind spots.",
        pitchFormat: "Small-sided pitch",
        cameraStyle: "phone",
        cameras: [
          { id: "camera-1", label: "Phone 1", x: 58, y: 3, rotation: 110, markerRotation: 68, coverageAngle: 70, coverageDepth: 72 },
          { id: "camera-2", label: "Phone 2", x: 42, y: 97, rotation: 290, markerRotation: 68, coverageAngle: 70, coverageDepth: 72 },
        ],
        notes: ["Record a clear synchronisation moment on both phones before kickoff.", "Check that neither angle is blocked by netting, posts or substitutes."],
        caption: "Choose this only where both positions are secure and permitted by the venue.",
      },
      {
        id: "opposite-touchlines-diagram",
        type: "pitchDiagram",
        title: "Opposite touchline coverage",
        description: "Phones positioned on opposite touchlines, each facing across the pitch to cover different areas.",
        pitchFormat: "Small-sided pitch",
        cameraStyle: "phone",
        cameras: [
          { id: "camera-1", label: "Phone 1", x: 3, y: 50, rotation: 330, markerRotation: 0, coverageAngle: 70, coverageDepth: 72 },
          { id: "camera-2", label: "Phone 2", x: 97, y: 50, rotation: 210, markerRotation: 0, coverageAngle: 70, coverageDepth: 72 },
        ],
        notes: ["Use elevated, secure mounting points where venue rules allow.", "Take a short test clip to check both goals and the main playing area are visible."],
        caption: "A practical option when a central mount is not available.",
      },
      {
        id: "mounts-by-venue",
        type: "affiliateProductCards",
        title: "Mount type by venue",
        disclosure: affiliateDisclosure,
        items: [
          { id: "budget-fence-mount", title: "Budget fence mount", bestFor: "Rigid fencing where the phone can be mounted safely outside the playing area.", experienceLevel: "tested", limitations: "Not suitable for loose netting or places where the phone could be struck by the ball.", paidLinkLabel: "Paid link", url: "https://amzn.to/44FurlS", ctaText: "View budget mount", lastChecked: "2026-07-23" },
          { id: "covered-fence-mount", title: "Covered fence mount", bestFor: "Outdoor venues where extra cover may help protect the phone from light weather exposure.", experienceLevel: "researched", limitations: "Does not remove the need for safe placement, venue permission or weather judgement.", paidLinkLabel: "Paid link", url: "https://amzn.to/4fpobUq", ctaText: "View covered mount", lastChecked: "2026-07-23" },
          { id: "post-mount", title: "Post mount", bestFor: "Secure posts where venue rules allow mounting outside the playing area.", experienceLevel: "researched", limitations: "Check post stability and make sure the mount cannot fall into the pitch or pedestrian routes.", paidLinkLabel: "Paid link", url: "https://amzn.to/4bnus1N", ctaText: "View post mount", lastChecked: "2026-07-23" },
        ],
      },
      {
        id: "blind-spots",
        type: "limitations",
        title: "Typical blind spots to check",
        items: ["Players blocking the view at pitch level.", "Action disappearing into a far corner.", "Goal-area obstruction.", "Substitutes or spectators walking across the lens.", "Netting, posts or fencing crossing the lens.", "Sun glare or rain on the lens.", "Excessive zoom.", "Mount movement caused by wind or impact."],
      },
      {
        id: "safety-checklist",
        type: "limitations",
        title: "Safety checklist",
        items: ["Confirm the venue allows recording and mounting equipment.", "Get the necessary recording consent before filming.", "Use landscape orientation.", "Keep both goals and the important playing area visible.", "Keep the mount outside the playing area and emergency routes.", "Check battery, storage and lens cleanliness.", "Record a short test clip and watch it before kickoff.", "Do not leave recording equipment unattended."],
      },
      {
        id: "mount-status",
        type: "notice",
        title: "Pitchside double-phone mount status",
        body: "Pitchside is developing its own double-phone mounting option for players and teams that want a more consistent two-phone setup. Compatibility, pricing and availability will be published after testing. Check Product Status for the latest confirmed status.",
      },
      {
        id: "faqs",
        type: "faq",
        items: [
          { question: "Is one phone enough to record a football match?", answer: "Yes, if a wide and stable view captures the important playing area. Use two phones when one angle leaves repeated blind spots." },
          { question: "Where should I position the phone?", answer: "Start with a central elevated position and adjust after watching a short test clip." },
          { question: "Can I attach a phone directly to football netting?", answer: "Usually no. Loose netting moves and can put the phone at risk. Use a secure post only if venue rules allow it." },
        ],
      },
      { id: "cta", type: "callToAction", headline: "Turn your recording into more than a video", description: "Pitchside is being built to connect suitable phone-recorded footage with supported match statistics, highlights, personal records and leaderboards.", buttonText: "Join the launch list", buttonUrl: "/contact" },
    ],
    author: { name: "Abdullah Luqman", url: "/authors/abdullah-luqman" },
    reviewer: { name: "Dave Coombs", url: "/authors/dave-coombs" },
    publishedAt: "2026-07-23T00:00:00.000Z",
    updatedAt: "2026-07-23T00:00:00.000Z",
  },
});
