export const videoAssets = {
  "private-beta-walkthrough": { videoId: "private-beta-walkthrough", title: "Private Beta App Walkthrough", description: "A private-beta walkthrough of the Pitchside feed, match result output and player search.", assetUrl: "/videos/pitchside-private-beta-app-walkthrough.mp4", posterUrl: "/videos/pitchside-private-beta-app-walkthrough.webp", duration: "PT45S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "The Pitchside Feed opens. A match result is opened to show a score, a match preview and labelled goal, assist, tackle, save and pass rows. The search view opens with account details redacted, then the Feed returns.", placement: "how-pitchside-ai-works", schemaEnabled: true },
  "match-analysis-player-review": { videoId: "match-analysis-player-review", title: "Match Analysis and Player Review", description: "A private-beta view of a match result and its labelled statistics.", assetUrl: "/videos/pitchside-match-analysis-player-review.mp4", posterUrl: "/videos/pitchside-match-analysis-player-review.webp", duration: "PT25S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "A match result opens with Team A and Team B scores, a match-video preview, and labelled rows for goals, assists, tackles, saves and passes. Important events and player assignments require review during private beta.", placement: "technology", schemaEnabled: true },
  "social-feed": { videoId: "social-feed", title: "Pitchside Social Feed", description: "A privacy-redacted private-beta Feed view.", assetUrl: "/videos/pitchside-social-feed.mp4", posterUrl: "/videos/pitchside-social-feed.webp", duration: "PT14S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "The Pitchside Feed opens and shows match activity. Personal account details are blurred.", placement: "grassroots-football-app", schemaEnabled: true },
  "add-friends": { videoId: "add-friends", title: "Add Friends in Pitchside", description: "A privacy-redacted private-beta player search view.", assetUrl: "/videos/pitchside-add-friends.mp4", posterUrl: "/videos/pitchside-add-friends.webp", duration: "PT15S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "The app search view opens. Search text, account names, profile imagery and keyboard suggestions are redacted. The recording shows search only, not a new friend request being sent.", placement: "grassroots-football-app", schemaEnabled: false },
  "share-with-friends": { videoId: "share-with-friends", title: "Share With Friends", description: "A private-beta match result view with the in-app Share action.", assetUrl: "/videos/pitchside-share-with-friends.mp4", posterUrl: "/videos/pitchside-share-with-friends.webp", duration: "PT14S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "A match result is open. The visible Share action is shown. The recording does not show a completed in-app destination, so no completed sharing claim is made.", placement: "grassroots-football-app", schemaEnabled: false },
  "homepage-app-teaser": { videoId: "homepage-app-teaser", title: "Pitchside Private Beta", description: "A silent private-beta teaser of the Pitchside app.", assetUrl: "/videos/pitchside-homepage-app-teaser.mp4", posterUrl: "/videos/pitchside-homepage-app-teaser.webp", duration: "PT9S", recordedAt: "2025-10-11", uploadedAt: "2026-08-04", authorName: "Pitchside AI", reviewerName: "Dave Coombs", statusLabel: "Private beta", transcript: "A silent sequence shows the Feed, a match result, a redacted search view and the Share action.", placement: "homepage", autoplay: true, loop: true, schemaEnabled: true },
};

export const videoPlacementIds = { "/technology": ["match-analysis-player-review"], "/technology/how-pitchside-ai-works": ["private-beta-walkthrough"], "/grassroots-football-app": ["social-feed", "add-friends", "share-with-friends"], "/football-analysis-app": ["match-analysis-player-review"], "/football-video-analysis": ["match-analysis-player-review"], "/ai-football-analysis": ["match-analysis-player-review"], "/ai-football-highlights": ["share-with-friends"], "/football-stats-app": ["match-analysis-player-review"], "/5-a-side-football": ["match-analysis-player-review"], "/record-football-matches": ["match-analysis-player-review"], "/football-camera-app": ["match-analysis-player-review"], "/best-veo-alternative-football": ["match-analysis-player-review"] };

export const frameEvidenceByRoute = {
  "/technology": { src: "/images/app-evidence/labelled-match-output.webp", alt: "Pitchside private-beta match output showing a score, match preview and labelled statistic rows", caption: "Private-beta match output: visible rows are labelled goals, assists, tackles, saves and passes. Review important events and player assignments before treating results as final." },
  "/football-analysis-app": { src: "/images/app-evidence/match-result-overview.webp", alt: "Pitchside private-beta match result overview", caption: "A match-result overview from the private beta. It shows reviewable output, not a guarantee of final automated results." },
  "/football-video-analysis": { src: "/images/app-evidence/review-match-result.webp", alt: "Pitchside private-beta review screen with match result and labelled rows", caption: "After suitable small-sided footage is processed, important events and player assignments still require review." },
  "/football-stats-app": { src: "/images/app-evidence/labelled-match-output.webp", alt: "Pitchside private-beta labelled match statistics", caption: "The visible labels describe the current private-beta match output. Processing can take up to 45 minutes and results depend on suitable footage." },
  "/5-a-side-football": { src: "/images/app-evidence/match-result-overview.webp", alt: "Pitchside private-beta match result displayed in the application", caption: "Example private-beta output for suitable 5, 6 and 7-a-side footage. Camera position, visibility, lighting and obstruction affect results." },
  "/record-football-matches": { src: "/images/app-evidence/review-match-result.webp", alt: "Pitchside private-beta match review result", caption: "A reviewable result appears after processing; the current private-beta workflow can take up to 45 minutes." },
  "/football-camera-app": { src: "/images/app-evidence/review-match-result.webp", alt: "Pitchside private-beta match review output", caption: "This shows a private-beta review screen after recording, not a substitute for every dedicated full-pitch camera system." },
  "/best-veo-alternative-football": { src: "/images/app-evidence/match-result-overview.webp", alt: "Pitchside private-beta match output displayed on a phone", caption: "Pitchside is currently focused on suitable small-sided footage during private beta; public availability is not confirmed." },
};
